name: Profile Metrics
on:
  schedule:
    - cron: "0 8 1/2 * *"
  workflow_dispatch:
  workflow_call:
    secrets:
      METRICS_TOKEN:
        required: true
      METRICS_TOKEN_WITH_SCOPES:
        required: true
      METRICS_TOKEN_PERSONAL:
        required: true
      CHESS_TOKEN:
        required: true
      PAGESPEED_TOKEN:
        required: true
      GOOGLE_MAP_TOKEN:
        required: true
      SPLATOON_TOKEN:
        required: true
      SPLATOON_STATINK_TOKEN:
        required: true
      SIXTEEN_PERSONALITIES_URL:
        required: true
      SPOTIFY_TOKENS:
        required: true
      STOCK_TOKEN:
        required: true
      TWITTER_TOKEN:
        required: true
      WAKATIME_TOKEN:
        required: true
jobs:

# ======================================================================================
# Renders
# ======================================================================================

  examples:
    runs-on: ubuntu-latest
    if: "github.repository == 'typ-AhmedSleem/typ-AhmedSleem'"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout examples
        run: git checkout examples

      - name: 🗃️ Base content - Default metrics
        uses: lowlighter/metrics@master
        with:
          filename: metrics.base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 🧱 Core - Organization
        uses: lowlighter/metrics@master
        with:
          filename: metrics.organization.svg
          user: github
          token: ${{ secrets.METRICS_TOKEN_WITH_SCOPES }}
          base: header, repositories
          output_action: none
          delay: 120
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 🧱 Core - Large display
        uses: lowlighter/metrics@master
        with:
          filename: metrics.large.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_display: large
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 🧱 Core - JSON metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.example.json
          token: ${{ secrets.METRICS_TOKEN }}
          config_output: json
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
      - name: 🧱 Core - PNG metrics
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.example.png
          token: ${{ secrets.METRICS_TOKEN }}
          config_output: png
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
      - name: 🧱 Core - Metrics insights
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.insights.html
          token: ${{ secrets.METRICS_TOKEN }}
          config_output: insights
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
      - name: 🧱 Core - Plugin error example
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.error.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_projects: yes
          plugins_errors_fatal: no
          output_action: none
          delay: 120
          user: lowlighter
        if: ${{ success() || failure() }}
      - name: 📅 Isometric commit calendar - Half-year calendar
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 📅 Isometric commit calendar - Full-year calendar
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 🈷️ Languages activity - Most used
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 4
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 🈷️ Languages activity - Most used (with details)
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.details.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 🈷️ Languages activity - Recently used
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.recent.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 4
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 🈷️ Languages activity - Indepth analysis
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: ✨ Stargazers - Using classic charts
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.stargazers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: ✨ Stargazers - Using graph charts
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.stargazers.graph.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: graph
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: ✨ Stargazers - With worldmap
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.stargazers.worldmap.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts: no
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
          plugin_stargazers_worldmap_sample: 200
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 👨‍💻 Lines of code changed - Compact display in base plugin
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          plugin_lines: yes
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: 👨‍💻 Lines of code changed - Repositories and diff history
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.lines.history.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_lines: yes
          plugin_lines_sections: repositories, history
          plugin_lines_repositories_limit: 2
          plugin_lines_history_limit: 1
          repositories_skipped: |
            @use.patterns
            */*
            +lowlighter/metrics
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
      - name: ⏰ WakaTime - WakaTime
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: MOCKED_TOKEN
          use_mocked_data: yes
          output_action: none
          delay: 120
          user: lowlighter
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
